import { zodResolver } from "@hookform/resolvers/zod";
import { type NextPage } from "next";
import Head from "next/head";
import { Fragment, useState, type FC } from "react";
import { type SubmitHandler, useForm } from "react-hook-form";
import { z } from "zod";
import { api } from "~/utils/api";
import Header from "./components/Header";

const Home: NextPage = () => {
  const { mutate: generateHaiku, isLoading } =
    api.example.generateHaiku.useMutation({
      onMutate: () => {
        setHaiku("");
        setError("");
      },
      onSuccess: (data) => {
        setError("");
        setHaiku(data);
        resetField("topic");
      },
      onError: (error) => {
        setError(error.message);
      },
    });

  const [haiku, setHaiku] = useState<string>("");
  const [error, setError] = useState<string>("");

  const onSubmit: SubmitHandler<FormSchema> = (data) => {
    console.log(data);
    generateHaiku({ topic: data.topic });
  };

  const formSchema = z.object({
    topic: z
      .string()
      .min(5, { message: "Please input at least 5 characters" })
      .max(100),
  });
  type FormSchema = z.infer<typeof formSchema>;

  const {
    register,
    handleSubmit,
    resetField,
    formState: { errors },
  } = useForm<FormSchema>({
    resolver: zodResolver(formSchema),
    mode: "onSubmit",
  });

  return (
    <>
      <Head>
        <title>Haiku Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex h-full min-h-screen flex-col items-center justify-center gap-10 p-6">
        <h1 className="text-center text-2xl font-bold">
          Write me a haiku about...
        </h1>

        <form
          // eslint-disable-next-line @typescript-eslint/no-misused-promises
          onSubmit={handleSubmit(onSubmit)}
          className="flex w-full max-w-xl flex-col justify-center gap-2"
        >
          <label htmlFor="topic" className="sr-only">
            Haiku topic
          </label>
          <input
            {...register("topic")}
            id="topic"
            type="text"
            placeholder="Danny Devito"
            max={100}
            className="rounded-lg border p-3 transition-colors hover:border-indigo-300"
          />
          {errors.topic && (
            <label className="text-red-700" htmlFor="topic">
              {errors.topic.message}
            </label>
          )}

          <button
            type="submit"
            className={`${
              isLoading ? "cursor-not-allowed opacity-50" : ""
            } rounded-md bg-indigo-500 p-3 font-bold text-white transition-colors hover:bg-indigo-600 active:bg-indigo-500`}
          >
            {isLoading ? <Spinner /> : "Generate"}
          </button>
        </form>
        <div className="relative h-40 w-full max-w-xl cursor-default rounded-md border border-indigo-200  p-10 text-center italic leading-6 transition-colors hover:border-indigo-300">
          <pre className="font-sans">{error ? error : haiku.trim()}</pre>
          <button
            hidden
            className="absolute top-1 right-1 rounded-md border border-indigo-200 bg-gray-100 px-2 py-1 text-sm transition-all hover:border-indigo-400"
          >
            save
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;

const Spinner: FC = () => {
  return (
    <div className="text-center">
      <div role="status">
        <svg
          aria-hidden="true"
          className="mr-2 inline h-4 w-4 animate-spin fill-gray-600 text-gray-200 dark:fill-gray-300 dark:text-gray-600"
          viewBox="0 0 100 101"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
            fill="currentColor"
          />
          <path
            d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
            fill="currentFill"
          />
        </svg>
        <span className="sr-only">Loading...</span>
      </div>
    </div>
  );
};
